title: 浸月之海
author: { name: Paro }
baseURL: https://paro.one/
defaultContentLanguage: zh-cn
hasCJKLanguage: true
disableHugoGeneratorInject: true

taxonomies:
  tag: tag
disableKinds: [taxonomy]
ignoreErrors: ["error-disable-taxonomy"]

paginate: 10
paginatePath: ''

markup:
  goldmark:
    extensions:
      typographer: false
    parser:
      attribute:
        block: true
    renderer:
      unsafe: true
  highlight:
    lineNos: true
    lineNumbersInTable: false
    noClasses: false
    style: solorized-dark
    tabWidth: 2
  tableOfContents:
    ordered: true
    startLevel: 2
    endLevel: 3

server:
  headers:
  - for: /**
    values:
      access-control-allow-origin: '*'
      cache-control: no-cache
