title: Paro 的博客
author: { name: Paro }
defaultContentLanguage: zh-cn
hasCJKLanguage: true
disableHugoGeneratorInject: true
baseURL: https://paro.one/
disableKinds: [taxonomy, term]
paginate: 10
theme: [base]
markup:
  goldmark:
    extensions:
      typographer: false
    parser:
      attribute:
        block: true
    renderer:
      unsafe: true
  highlight:
    lineNos: true
    noClasses: false
    style: solorized-dark
    tabWidth: 2
  tableOfContents:
    ordered: true
    startLevel: 2
    endLevel: 3
server:
  headers:
  - for: /**
    values:
      access-control-allow-origin: '*'
      cache-control: no-cache
