title: Paro 的世界
defaultContentLanguage: zh-cn
taxonomies:
  tag: tags
params:
  comment:
    <em>请转到
    <a href="https://github.com/paro-zo/blog/issues" target="_blank">issues</a>
    页发表评论。</em>

baseURL: https://paro-zo.github.io/
#enableGitInfo: true
markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    lineNos: true
    noClasses: false
    style: solorized-dark
    tabWidth: 2
  tableOfContents:
    ordered: true
    startLevel: 2
    endLevel: 3
